FROM buildpack-deps:centos7-scm

RUN set -ex; \
	yum install -y \
		autoconf \
		automake \
		bzip2 \
		file \
		gcc-c++ \
		gcc \
		ImageMagick \
		bzip2-devel \
		glibc-devel \
		libcurl-devel \
		libdb-devel \
		libevent \
		libffi-devel \
		gdbm-devel \
		GeoIP \
		glib2-devel \
		libjpeg-devel \
		krb5-devel \
		xz-devel \
		ImageMagick-c++ \
		ImageMagick-perl \
		ncurses-devel \
		libpng-devel \
		postgresql-devel \
		readline-devel \
		sqlite-devel \
		openssl-devel gnutls-devel \
		libtool \
		libwebp \
		libxml2-devel \
		libxslt-devel \
		libyaml \
		make \
		patch \
		xz \
		zlib-devel \
		\
		mariadb-devel \
		mariadb-libs \
	; \
	yum clean all
